### ISSUE TITLE
如何切换前后摄像头

### ISSUE THREAD

**Issue by AllenLucas** [junerver/VideoRecorder#2]
不太清楚这里如何切换前后摄像头，求助

**Comment by junerver** [comment]
如果只是换成使用前置摄像头只需要将Camera.open(Camera.CameraInfo.CAMERA_FACING_BACK)改成Camera.CameraInfo.CAMERA_FACING_FRONT，同时将录像MediaRecorder的旋转角度改成setOrientationHint(270) 270度，需要注意的是 前置摄像头的预览时是镜像的，但最终输出不是镜像的。

**Comment by AllenLucas** [comment]
> 如果只是换成使用前置摄像头只需要将Camera.open(Camera.CameraInfo.CAMERA_FACING_BACK)改成Camera.CameraInfo.CAMERA_FACING_FRONT，同时将录像MediaRecorder的旋转角度改成setOrientationHint(270) 270度，需要注意的是 前置摄像头的预览时是镜像的，但最终输出不是镜像的。

好的。谢谢
