### ISSUE TITLE
目前使用是否稳定

### ISSUE THREAD

**Issue by Wudelin** [junerver/VideoRecorder#3]

**Comment by junerver** [comment]
使用的都是系统自带API，兼容性较好，目前在我们项目上使用暂时没有问题。

**Comment by junerver** [comment]
> _No description provided._
使用的都是系统自带API，兼容性较好，目前在我们项目上使用暂时没有问题。

**Comment by Wudelin** [comment]
现在我把SurfaceView设置成260*260，录制的时候会变形，有什么办法可以解决吗？还有就是切换摄像头的时候录制 播放时会旋转180

**Comment by junerver** [comment]
> 现在我把SurfaceView设置成260*260，录制的时候会变形，有什么办法可以解决吗？还有就是切换摄像头的时候录制 播放时会旋转180

问题一是因为摄像头采集出来的图像并不是正方形的，所以在surfaceview上预览会被挤压变形。
问题二是因为摄像头采集的图像并不是竖直的，我的代码实例中使用的是后置摄像头，需要旋转90度处理。请参考文章https://blog.csdn.net/qq_36391075/article/details/80503619。

**Comment by Wudelin** [comment]
我现在录制完后正常播放，但是我想点击取消按钮后重新进入预览界面，老是提示Android Camera startPreview failed。。。。。请问是什么原因
